### PR TITLE
fix: dont panic inside implementation

### PR DESCRIPTION
**Pull request by HigherOrderLogic**
As the PR title said. The reason for this is that I don't want my code to panic because of some macro implementation.

Todo

- [ ] Add test
- [ ] Better error (maybe?)

### CODE REVIEW

**Comment by murar8** [comment]
Hi, sorry for the delay, thank you for your contribution! Unfortunately I was not aware that multipart/form-data supports nameless fields. Your implementation makes perfect sense to me because I really don't see a way to assign a field to a struct field without having a name. I would add a couple tests though so we don't have regressions. If you don't have time I can add them during the weekend.

**Review by murar8 — CHANGES_REQUESTED** [review]
- I would structure the logic in such a way that the field is ignored in lax mode and throw the error in strict mode.
- I would mention it on the docs.
- Needs a test for the macro in `macros/tests` and a test in `src/typed_multipart_error.rs`. 
- What do you have in mind for a better error?

**Comment by HigherOrderLogic** [comment]
> What do you have in mind for a better error?
I'm thinking about providing some extra information with the error, like the data that go with that nameless field, but currently I'm struggling to do that.

**Comment by murar8** [comment]
> I'm thinking about providing some extra information with the error, like the data that go with that nameless field, but currently I'm struggling to do that.

Do you think that would be useful? I can't think of a use case for the data, in my opinion the way you wrote it is good.

**Comment by murar8** [comment]
Since I have some free time I will move the development of this fix to #53, thank you for the contribution!

**Pull request closed without merging**
